In [3]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import ast
import numpy as np

In [4]:
disease_dict = {
    'D010300': 'Parkinsons',
    'D000544': 'Alzheimers',
    'D001327': 'Autoimmune Diseases',
    'D008881': 'Migrane Disorders',
    'D007410': 'Intestinal Diseases',
    'D001714': 'Bipolar Disorder',
    'D003863': 'Depression', 
    'D008171': 'Lung Diseases', 
    'D012559': 'Schizophrenia', 
    'D013959': 'Thyroid Diseases',
    'D043183': 'Irritable Bowel Syndrome', 
    'D002318': 'Cardiovascular Diseases', 
    'D001289': 'Attention Deficit Disorder with Hyperactivity',  
    'D003248': 'Constipation', 
    'D002446': 'Celiac Disease', 
    'D003920': 'Diabetes Mellitus', 
    'D003967': 'Diarrhea', 
    'D008107': 'Liver Diseases', 
    'D015212': 'Inflammatory Bowel Diseases', 
    'D007674': 'Kidney Diseases',
    'D003015': 'Clostridium Infections', 
    'D000067877': 'Autism Spectrum Disorder', 
    'D004827': 'Epilepsy', 
    'D010661': 'Phenylketonurias',
    'D006262': 'Health'
    
}

### Schizophrenia Male

In [5]:
sch_male_df = pd.read_csv('schizophrenia_male.csv')
sch_male_df.head()

Run ID   Sex    BMI  Age                   Country  \
0  ERR1072629  Male  17.67   64  United States of America   
1  ERR1072937  Male  26.51   53  United States of America   
2  ERR1073491  Male  28.08   49  United States of America   
3  ERR1075554  Male  30.74   62  United States of America   
4  ERR1075686  Male  45.84   56  United States of America   

                                             Mesh ID  Abiotrophia  \
0  ['D001714', 'D003863', 'D007410', 'D008171', '...     0.000000   
1       ['D001714', 'D002318', 'D003863', 'D012559']     0.000000   
2                  ['D001714', 'D003863', 'D012559']     0.003157   
3  ['D001289', 'D001714', 'D003863', 'D008881', '...     0.000000   
4       ['D001714', 'D003863', 'D008171', 'D012559']     0.000000   

   Acanthopleuribacter  Acetoanaerobium  Acetobacter  ...  Weissella  \
0                  0.0              0.0          0.0  ...        0.0   
1                  0.0              0.0          0.0  ...        0.0   
2                  0.0              0.0          0.0  ...        0.0   
3                  0.0              0.0          0.0  ...        0.0   
4                  0.0              0.0          0.0  ...        0.0   

   Wenyingzhuangia  Wenzhouxiangella  Wolbachia  Xanthomonas  Xenorhabdus  \
0              0.0               0.0        0.0          0.0          0.0   
1              0.0               0.0        0.0          0.0          0.0   
2              0.0               0.0        0.0          0.0          0.0   
3              0.0               0.0        0.0          0.0          0.0   
4              0.0               0.0        0.0          0.0          0.0   

   Yersinia  Youngiibacter  Zoogloea  Zymomonas  
0       0.0            0.0   0.00484        0.0  
1       0.0            0.0   0.00000        0.0  
2       0.0            0.0   0.00000        0.0  
3       0.0            0.0   0.00000        0.0  
4       0.0            0.0   0.00000        0.0  

[5 rows x 773 columns]

In [6]:
sch_male_df.isnull().sum()

Run ID           0
Sex              0
BMI              0
Age              0
Country          0
                ..
Xenorhabdus      0
Yersinia         0
Youngiibacter    0
Zoogloea         0
Zymomonas        0
Length: 773, dtype: int64

In [7]:
sch_male_df['BMI'].unique()

array([  17.67,   26.51,   28.08,   30.74,   45.84,   20.28,   22.72,
         20.62,   31.47,   27.37,    0.  ,   26.54,   23.49,   21.52,
         22.24,   33.12,   23.18,   25.1 ,   23.99,   22.84,   20.06,
         40.32,   16.98,   31.97,   24.49,   23.75,   22.15,   19.14,
         25.33,   24.41,   25.38,   24.33,   32.14, 4101.24,   21.29,
         19.61,   22.87,   29.99,   25.09,   30.27,   23.59,   26.26,
         29.68,   21.91,   28.09,   24.99,   23.71,   32.92,   20.45,
         24.68,   28.76,   24.48,   20.89,   27.32,   25.21,   20.52,
         33.72,   27.69,   28.35,   27.98,   24.37,   28.75,   22.28,
         23.24,   24.58,   23.06,   45.19,   29.57,   22.05,   33.47,
         21.62,   27.02,   20.8 ,   24.39,   33.91,   28.97,   32.22,
         29.84,   28.12,   25.4 ,   24.8 ,   21.95,   20.97,   25.82,
         29.41])

In [8]:
# replace the BMI's 0 and 4100 with the medians of the rest 

sch_male_bmi_filter = sch_male_df[(sch_male_df['BMI'] > 1) & (sch_male_df['BMI'] < 50)]
sch_male_bmi_median = sch_male_bmi_filter['BMI'].median()
sch_male_df['BMI'] = sch_male_df['BMI'].replace([0, 4101.24], sch_male_bmi_median)

sch_male_df.head()

Run ID   Sex    BMI  Age                   Country  \
0  ERR1072629  Male  17.67   64  United States of America   
1  ERR1072937  Male  26.51   53  United States of America   
2  ERR1073491  Male  28.08   49  United States of America   
3  ERR1075554  Male  30.74   62  United States of America   
4  ERR1075686  Male  45.84   56  United States of America   

                                             Mesh ID  Abiotrophia  \
0  ['D001714', 'D003863', 'D007410', 'D008171', '...     0.000000   
1       ['D001714', 'D002318', 'D003863', 'D012559']     0.000000   
2                  ['D001714', 'D003863', 'D012559']     0.003157   
3  ['D001289', 'D001714', 'D003863', 'D008881', '...     0.000000   
4       ['D001714', 'D003863', 'D008171', 'D012559']     0.000000   

   Acanthopleuribacter  Acetoanaerobium  Acetobacter  ...  Weissella  \
0                  0.0              0.0          0.0  ...        0.0   
1                  0.0              0.0          0.0  ...        0.0   
2                  0.0              0.0          0.0  ...        0.0   
3                  0.0              0.0          0.0  ...        0.0   
4                  0.0              0.0          0.0  ...        0.0   

   Wenyingzhuangia  Wenzhouxiangella  Wolbachia  Xanthomonas  Xenorhabdus  \
0              0.0               0.0        0.0          0.0          0.0   
1              0.0               0.0        0.0          0.0          0.0   
2              0.0               0.0        0.0          0.0          0.0   
3              0.0               0.0        0.0          0.0          0.0   
4              0.0               0.0        0.0          0.0          0.0   

   Yersinia  Youngiibacter  Zoogloea  Zymomonas  
0       0.0            0.0   0.00484        0.0  
1       0.0            0.0   0.00000        0.0  
2       0.0            0.0   0.00000        0.0  
3       0.0            0.0   0.00000        0.0  
4       0.0            0.0   0.00000        0.0  

[5 rows x 773 columns]

In [9]:
sch_male_df['BMI'].unique()

array([17.67, 26.51, 28.08, 30.74, 45.84, 20.28, 22.72, 20.62, 31.47,
       27.37, 24.68, 26.54, 23.49, 21.52, 22.24, 33.12, 23.18, 25.1 ,
       23.99, 22.84, 20.06, 40.32, 16.98, 31.97, 24.49, 23.75, 22.15,
       19.14, 25.33, 24.41, 25.38, 24.33, 32.14, 21.29, 19.61, 22.87,
       29.99, 25.09, 30.27, 23.59, 26.26, 29.68, 21.91, 28.09, 24.99,
       23.71, 32.92, 20.45, 28.76, 24.48, 20.89, 27.32, 25.21, 20.52,
       33.72, 27.69, 28.35, 27.98, 24.37, 28.75, 22.28, 23.24, 24.58,
       23.06, 45.19, 29.57, 22.05, 33.47, 21.62, 27.02, 20.8 , 24.39,
       33.91, 28.97, 32.22, 29.84, 28.12, 25.4 , 24.8 , 21.95, 20.97,
       25.82, 29.41])

In [10]:
sch_male_df['Age'].unique()

array([64, 53, 49, 62, 56, 39, 67, 73,  0, 71, 54, 23, 40, 35, 38, 42, 43,
       21, 61, 34, 72, 27, 32, 25, 24, 65, 47, 51, 63, 46, 52, 45, 68, 48,
       57, 70, 29, 58, 37, 36, 41, 28, 50, 17, 31, 55, 30, 12, 76])

In [11]:
# replace 0 with the median 

sch_male_age_filter = sch_male_df[sch_male_df['Age'] > 1]
sch_male_age_median = sch_male_age_filter['Age'].median()
sch_male_df['Age'] = sch_male_df['Age'].replace(0, sch_male_age_median)

sch_male_df.head()

Run ID   Sex    BMI  Age                   Country  \
0  ERR1072629  Male  17.67   64  United States of America   
1  ERR1072937  Male  26.51   53  United States of America   
2  ERR1073491  Male  28.08   49  United States of America   
3  ERR1075554  Male  30.74   62  United States of America   
4  ERR1075686  Male  45.84   56  United States of America   

                                             Mesh ID  Abiotrophia  \
0  ['D001714', 'D003863', 'D007410', 'D008171', '...     0.000000   
1       ['D001714', 'D002318', 'D003863', 'D012559']     0.000000   
2                  ['D001714', 'D003863', 'D012559']     0.003157   
3  ['D001289', 'D001714', 'D003863', 'D008881', '...     0.000000   
4       ['D001714', 'D003863', 'D008171', 'D012559']     0.000000   

   Acanthopleuribacter  Acetoanaerobium  Acetobacter  ...  Weissella  \
0                  0.0              0.0          0.0  ...        0.0   
1                  0.0              0.0          0.0  ...        0.0   
2                  0.0              0.0          0.0  ...        0.0   
3                  0.0              0.0          0.0  ...        0.0   
4                  0.0              0.0          0.0  ...        0.0   

   Wenyingzhuangia  Wenzhouxiangella  Wolbachia  Xanthomonas  Xenorhabdus  \
0              0.0               0.0        0.0          0.0          0.0   
1              0.0               0.0        0.0          0.0          0.0   
2              0.0               0.0        0.0          0.0          0.0   
3              0.0               0.0        0.0          0.0          0.0   
4              0.0               0.0        0.0          0.0          0.0   

   Yersinia  Youngiibacter  Zoogloea  Zymomonas  
0       0.0            0.0   0.00484        0.0  
1       0.0            0.0   0.00000        0.0  
2       0.0            0.0   0.00000        0.0  
3       0.0            0.0   0.00000        0.0  
4       0.0            0.0   0.00000        0.0  

[5 rows x 773 columns]

In [12]:
sch_male_df['Age'].unique()

array([64, 53, 49, 62, 56, 39, 67, 73, 48, 71, 54, 23, 40, 35, 38, 42, 43,
       21, 61, 34, 72, 27, 32, 25, 24, 65, 47, 51, 63, 46, 52, 45, 68, 57,
       70, 29, 58, 37, 36, 41, 28, 50, 17, 31, 55, 30, 12, 76])

In [13]:
sch_male_df['Country'].unique()

array(['United States of America', 'United Kingdom', 'Australia',
       'Sweden', 'Canada', 'New Zealand'], dtype=object)

In [14]:
mesh_id_sch_male_df = sch_male_df['Mesh ID'].unique()

In [15]:
mesh_ids_series_sch_male = pd.Series(sch_male_df['Mesh ID'])
flattened_mesh_ids_sch_male = [item for sublist in mesh_ids_series_sch_male.apply(ast.literal_eval) for item in sublist]
unique_mesh_ids_sch_male = pd.Series(flattened_mesh_ids_sch_male).unique()
unique_mesh_ids_sch_male


array(['D001714', 'D003863', 'D007410', 'D008171', 'D012559', 'D013959',
       'D043183', 'D002318', 'D001289', 'D008881', 'D003248', 'D002446',
       'D003920', 'D003967', 'D008107', 'D001327', 'D015212', 'D007674',
       'D003015', 'D000067877', 'D004827', 'D010661'], dtype=object)

In [16]:
mapped_diseases_sch_male = [
    [disease_dict[code.strip("[]' ")] for code in disease_list.split(',')]
    for disease_list in unique_mesh_ids_sch_male
]

print(mapped_diseases_sch_male)

[['Bipolar Disorder'], ['Depression'], ['Intestinal Diseases'], ['Lung Diseases'], ['Schizophrenia'], ['Thyroid Diseases'], ['Irritable Bowel Syndrome'], ['Cardiovascular Diseases'], ['Attention Deficit Disorder with Hyperactivity'], ['Migrane Disorders'], ['Constipation'], ['Celiac Disease'], ['Diabetes Mellitus'], ['Diarrhea'], ['Liver Diseases'], ['Autoimmune Diseases'], ['Inflammatory Bowel Diseases'], ['Kidney Diseases'], ['Clostridium Infections'], ['Autism Spectrum Disorder'], ['Epilepsy'], ['Phenylketonurias']]


In [22]:
bacteria_sch_male_df = sch_male_df.drop(['Run ID', 'Sex', 'BMI', 'Age', 'Country', 'Mesh ID'], axis=1)
att_sch_male_columns = ['Run ID', 'Sex', 'BMI', 'Age', 'Country', 'Mesh ID']
att_sch_male_df = sch_male_df[att_sch_male_columns]

zero_counts_sch_male = (bacteria_sch_male_df == 0.0).sum()
zero_counts_sch_male

Abiotrophia            89
Acanthopleuribacter    98
Acetoanaerobium        99
Acetobacter            99
Acetobacterium         99
                       ..
Xenorhabdus            83
Yersinia               75
Youngiibacter          98
Zoogloea               92
Zymomonas              98
Length: 767, dtype: int64

In [23]:
threshold_sch_male = 0.2 * len(bacteria_sch_male_df)
filtered_sch_male = zero_counts_sch_male[zero_counts_sch_male <= threshold_sch_male]
filtered_sch_male

Akkermansia               17
Alistipes                  3
Anaerofilum               18
Anaerotruncus              9
Bacillus                   2
Bacteroides                0
Barnesiella               11
Bifidobacterium            5
Blautia                    0
Clostridium                2
Coprococcus                9
Desulfovibrio             15
Dialister                 17
Dorea                     14
Erysipelatoclostridium     6
Eubacterium                2
Faecalibacterium           0
Holdemania                16
Intestinibacter           19
Lachnoclostridium          0
Lactobacillus             15
Odoribacter               13
Oscillibacter              2
Parabacteroides            2
Prevotella                 1
Pseudomonas               12
Roseburia                  2
Ruminococcus               3
Sporobacter                7
Streptococcus              2
Unknown                    0
dtype: int64

In [24]:
filtered_sch_male = zero_counts_sch_male[zero_counts_sch_male <= threshold_sch_male]

filtered_sch_male_df = bacteria_sch_male_df[filtered_sch_male.index]

filtered_sch_male = pd.concat([att_sch_male_df, filtered_sch_male_df], axis=1)

filtered_sch_male.to_csv('clean_schizophrenia_male.csv')

filtered_sch_male.shape

(100, 37)

In [25]:
filtered_sch_male.head()

Run ID   Sex    BMI  Age                   Country  \
0  ERR1072629  Male  17.67   64  United States of America   
1  ERR1072937  Male  26.51   53  United States of America   
2  ERR1073491  Male  28.08   49  United States of America   
3  ERR1075554  Male  30.74   62  United States of America   
4  ERR1075686  Male  45.84   56  United States of America   

                                             Mesh ID  Akkermansia  Alistipes  \
0  ['D001714', 'D003863', 'D007410', 'D008171', '...     2.158450   17.50470   
1       ['D001714', 'D002318', 'D003863', 'D012559']     0.031791    1.01733   
2                  ['D001714', 'D003863', 'D012559']     0.176768    5.60290   
3  ['D001289', 'D001714', 'D003863', 'D008881', '...     0.360811    3.15526   
4       ['D001714', 'D003863', 'D008171', 'D012559']     0.037344    4.91069   

   Anaerofilum  Anaerotruncus  ...  Odoribacter  Oscillibacter  \
0     0.033877       0.159706  ...     1.408310       1.974540   
1     0.005299       0.105971  ...     0.243734       0.927251   
2     0.025253       0.126263  ...     2.077020       0.656566   
3     0.044181       0.191451  ...     0.250359       2.032330   
4     0.012448       1.163880  ...     0.485467       0.553930   

   Parabacteroides  Prevotella  Pseudomonas  Roseburia  Ruminococcus  \
0        11.494000    0.029037     0.024198   0.503315      1.456710   
1         0.222540    0.052986    41.169900   0.090076      0.021194   
2         3.936240    0.022096     0.018939   0.407197      6.177400   
3         0.025772    0.147270     0.003682   1.395380      0.209860   
4         1.350590    0.024896     1.674240   0.149374      1.275910   

   Sporobacter  Streptococcus  Unknown  
0     0.198422       0.004840  21.9813  
1     0.111270       0.598739  10.1733  
2     0.085227       0.050505  11.0574  
3     0.224587       0.206178  25.9674  
4     0.908695       0.037344  55.3059  

[5 rows x 37 columns]

In [26]:
for mesh_id_str in filtered_sch_male['Mesh ID']:
    mesh_id_list = ast.literal_eval(mesh_id_str)
    
    mesh_id_string = ', '.join(mesh_id_list)
    
def format_mesh_ids(mesh_id_str):
    mesh_id_list = ast.literal_eval(mesh_id_str)
    return ', '.join(mesh_id_list)

filtered_sch_male['Mesh ID'] = filtered_sch_male['Mesh ID'].apply(format_mesh_ids)

def replace_mesh_ids_with_diseases(mesh_ids_str):
    mesh_ids = mesh_ids_str.split(', ')
    disease_names = [disease_dict.get(mesh_id, "Unknown Disease") for mesh_id in mesh_ids]
    return ', '.join(disease_names)

filtered_sch_male['Mesh ID'] = filtered_sch_male['Mesh ID'].apply(replace_mesh_ids_with_diseases)

filtered_sch_male.rename(columns={'Mesh ID': 'Condition'}, inplace=True)

filtered_sch_male.to_csv('clean_schizophrenia_male_condition.csv')

filtered_sch_male.head()

Run ID   Sex    BMI  Age                   Country  \
0  ERR1072629  Male  17.67   64  United States of America   
1  ERR1072937  Male  26.51   53  United States of America   
2  ERR1073491  Male  28.08   49  United States of America   
3  ERR1075554  Male  30.74   62  United States of America   
4  ERR1075686  Male  45.84   56  United States of America   

                                           Condition  Akkermansia  Alistipes  \
0  Bipolar Disorder, Depression, Intestinal Disea...     2.158450   17.50470   
1  Bipolar Disorder, Cardiovascular Diseases, Dep...     0.031791    1.01733   
2        Bipolar Disorder, Depression, Schizophrenia     0.176768    5.60290   
3  Attention Deficit Disorder with Hyperactivity,...     0.360811    3.15526   
4  Bipolar Disorder, Depression, Lung Diseases, S...     0.037344    4.91069   

   Anaerofilum  Anaerotruncus  ...  Odoribacter  Oscillibacter  \
0     0.033877       0.159706  ...     1.408310       1.974540   
1     0.005299       0.105971  ...     0.243734       0.927251   
2     0.025253       0.126263  ...     2.077020       0.656566   
3     0.044181       0.191451  ...     0.250359       2.032330   
4     0.012448       1.163880  ...     0.485467       0.553930   

   Parabacteroides  Prevotella  Pseudomonas  Roseburia  Ruminococcus  \
0        11.494000    0.029037     0.024198   0.503315      1.456710   
1         0.222540    0.052986    41.169900   0.090076      0.021194   
2         3.936240    0.022096     0.018939   0.407197      6.177400   
3         0.025772    0.147270     0.003682   1.395380      0.209860   
4         1.350590    0.024896     1.674240   0.149374      1.275910   

   Sporobacter  Streptococcus  Unknown  
0     0.198422       0.004840  21.9813  
1     0.111270       0.598739  10.1733  
2     0.085227       0.050505  11.0574  
3     0.224587       0.206178  25.9674  
4     0.908695       0.037344  55.3059  

[5 rows x 37 columns]